import Layout from '@/components/layout/Layoutzz'
import SidebarMenu from '@/components/layout/menu/sidebarMenu'
import SidebarNav from '@/components/layout/layout'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Layout /> */}
      <SidebarNav />
          {/* <SidebarMenu key={1} >

          </SidebarMenu> */}
    </>
  )
}
