import Head from 'next/head';

import Layout from '@/components/layout/layout';

export default function Home() {
  return (
    <>
      <Head>
        <title>App | Vendas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Layout /> */}
      <Layout />
      {/* <SidebarMenu key={1} >

          </SidebarMenu> */}
    </>
  );
}
